### ISSUE TITLE
Error in if (d0arg > 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by neginsheybani** [ntyet/rmRNAseq#1]
Hi,
I run the package for RNAseq count data  with the variables including time, condition and id. but it gives me an error "
![image](https://user-images.githubusercontent.com/124732096/220782779-832fb49e-aa96-47c2-803d-842e528c86e3.png)"

could you please help me how to figure this out?
Thank you!
Negin

**Comment by ntyet** [comment]
Hello,
Can you please provide a reproducible example? It would help me to check
what causes the error.
Thanks,
Yet

**Comment by ntyet** [comment]
issue resolved
